/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error": "#ba1a1a",
        "surface-container-highest": "#d3e4fe",
        "primary-fixed": "#9cf2e8",
        "inverse-on-surface": "#eaf1ff",
        "surface-container": "#e5eeff",
        "on-primary-fixed": "#00201d",
        "tertiary-fixed-dim": "#93ccff",
        "on-secondary-fixed": "#111c2d",
        "on-surface": "#0b1c30",
        "on-background": "#0b1c30",
        "background": "#f8f9ff",
        "on-surface-variant": "#3e4947",
        "surface": "#f8f9ff",
        "on-tertiary": "#ffffff",
        "outline-variant": "#bdc9c6",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "primary-container": "#0f766e",
        "surface-container-high": "#dce9ff",
        "on-tertiary-container": "#dbecff",
        "inverse-surface": "#213145",
        "tertiary": "#005683",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#d8e3fb",
        "on-error-container": "#93000a",
        "on-secondary-container": "#586377",
        "primary": "#005c55",
        "secondary-container": "#d5e0f8",
        "surface-container-low": "#eff4ff",
        "on-tertiary-fixed": "#001d31",
        "secondary": "#545f73",
        "surface-tint": "#006a63",
        "on-primary-container": "#a3faef",
        "surface-bright": "#f8f9ff",
        "on-secondary-fixed-variant": "#3c475a",
        "secondary-fixed-dim": "#bcc7de",
        "surface-dim": "#cbdbf5",
        "tertiary-fixed": "#cce5ff",
        "outline": "#6e7977",
        "on-primary": "#ffffff",
        "inverse-primary": "#80d5cb",
        "surface-variant": "#d3e4fe",
        "primary-fixed-dim": "#80d5cb",
        "tertiary-container": "#006fa8",
        "on-tertiary-fixed-variant": "#004b73",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#00504a"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "space-base": "1rem",
        "space-sm": "0.5rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-md": "0.75rem",
        "margin-lg": "4rem",
        "margin": "2rem",
        "gutter-sm": "0.75rem",
        "space-xs": "0.25rem",
        "space-2xs": "0.125rem",
        "margin-sm": "1rem",
        "gutter": "1.5rem",
        "space-2xl": "3rem",
        "gutter-lg": "2rem"
      },
      fontFamily: {
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "mono-metric": ["JetBrains Mono", "monospace"],
        "label-md": ["Inter", "sans-serif"],
        "mono-code": ["JetBrains Mono", "monospace"],
        "display-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "display": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["20px", { "lineHeight": "28px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "headline-lg": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "24px", "letterSpacing": "-0.011em", "fontWeight": "400" }],
        "mono-metric": ["11px", { "lineHeight": "14px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "label-md": ["13px", { "lineHeight": "16px", "letterSpacing": "0em", "fontWeight": "500" }],
        "mono-code": ["13px", { "lineHeight": "18px", "letterSpacing": "0em", "fontWeight": "400" }],
        "display-mobile": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "body-md": ["14px", { "lineHeight": "22px", "letterSpacing": "-0.006em", "fontWeight": "400" }],
        "body-sm": ["13px", { "lineHeight": "18px", "letterSpacing": "-0.004em", "fontWeight": "400" }],
        "label-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.03em", "fontWeight": "600" }],
        "display": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.025em", "fontWeight": "600" }],
        "headline-sm": ["16px", { "lineHeight": "24px", "letterSpacing": "-0.01em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
